services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "3001:3001"
    networks:
      - app-network

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "3002:3002"
    networks:
      - app-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
